remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Harshit Kandoi
logo: /assets/Circle_2.png
description: >
  Aspiring Data Scientist passionate about building data-driven solutions.  
  ğŸŒ [Visit My GitHub Profile](https://github.com/Harshit-Kandoi)  
  ğŸ“„ [Download My Resume](https://github.com/Harshit-Kandoi/Portfolio/assets/Resume.pdf)  

show_downloads: false  # Disabled for the project repo
theme: jekyll-theme-minimal
